# Generated by Django 5.2.5 on 2025-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
